import cardImage from "@/assets/cardImage.png";

export const campaigns = [
  {
    id: "1",
    title: "Clean Water for Rural Communities",
    shortDescription:
      "Help provide clean drinking water to rural communities facing water scarcity.",
    creator: "Alixa",
    submitted_date: "11-05-2023",
    image: cardImage,
    category: "environment",
    raised: 12500,
    goal: 25000,
    daysLeft: 15,
    status: "Approved",
  },
  {
    title: "Clean Water for Rural Communities",
    shortDescription:
      "Help provide clean drinking water to rural communities facing water scarcity.",
    creator: "Alixa",
    submitted_date: "11-05-2023",
    image: cardImage,
    category: "environment",
    raised: 12500,
    goal: 25000,
    daysLeft: 15,
    status: "Approved",
  },
  {
    title: "Clean Water for Rural Communities",
    shortDescription:
      "Help provide clean drinking water to rural communities facing water scarcity.",
    creator: "Alixa",
    submitted_date: "11-05-2023",
    image: cardImage,
    category: "environment",
    raised: 12500,
    goal: 25000,
    daysLeft: 15,
    status: "Approved",
  },
  {
    title: "Clean Water for Rural Communities",
    shortDescription:
      "Help provide clean drinking water to rural communities facing water scarcity.",
    creator: "Alixa",
    submitted_date: "11-05-2023",
    image: cardImage,
    category: "environment",
    raised: 12500,
    goal: 25000,
    daysLeft: 15,
    status: "Approved",
  },
  {
    title: "Clean Water for Rural Communities",
    shortDescription:
      "Help provide clean drinking water to rural communities facing water scarcity.",
    creator: "Alixa",
    submitted_date: "11-05-2023",
    image: cardImage,
    category: "environment",
    raised: 12500,
    goal: 25000,
    daysLeft: 15,
    status: "Pending",
  },
  {
    title: "Clean Water for Rural Communities",
    shortDescription:
      "Help provide clean drinking water to rural communities facing water scarcity.",
    creator: "Alixa",
    submitted_date: "11-05-2023",
    image: cardImage,
    category: "environment",
    raised: 12500,
    goal: 25000,
    daysLeft: 15,
    status: "Pending",
  },
  {
    title: "Clean Water for Rural Communities",
    shortDescription:
      "Help provide clean drinking water to rural communities facing water scarcity.",
    creator: "Alixa",
    submitted_date: "11-05-2023",
    image: cardImage,
    category: "environment",
    raised: 12500,
    goal: 25000,
    daysLeft: 15,
    status: "Pending",
  },
  {
    title: "Clean Water for Rural Communities",
    shortDescription:
      "Help provide clean drinking water to rural communities facing water scarcity.",
    creator: "Alixa",
    submitted_date: "11-05-2023",
    image: cardImage,
    category: "environment",
    raised: 12500,
    goal: 25000,
    daysLeft: 15,
    status: "Pending",
  },
  {
    title: "Clean Water for Rural Communities",
    shortDescription:
      "Help provide clean drinking water to rural communities facing water scarcity.",
    creator: "Alixa",
    submitted_date: "11-05-2023",
    image: cardImage,
    category: "environment",
    raised: 12500,
    goal: 25000,
    daysLeft: 15,
    status: "Pending",
  },
];
